In [1]:
import pandas as pd

In [2]:
bookings = pd.read_csv('bookings.csv', sep=',')
bookings

,Unnamed: 0,hotel,location,rating,review,no_of_reviews,room_score,price,room_category,balcony,sea_view,shared_bathroom,no_window,bed_count,bed_type
0,0,Krabi La Playa Resort - SHA Plus,Ao Nang Beach,8.2,Very Good,141.0,8.6,146026,Deluxe,0,0,0,0,1,double
1,1,KC Beach Club & Pool Villas,"Chaweng City Center , Chaweng",7.1,Good,193.0,0.0,215304,Double,1,1,0,0,1,queen bed
2,2,Rawai VIP Villas & Kids Park,Rawai Beach,8.3,Very Good,63.0,8.9,435384,Unknown,0,0,0,0,2,queen beds
3,3,"FuramaXclusive Sathorn, Bangkok","Bang Rak, Bangkok",7.7,Good,1.0,8.1,146240,Double,0,0,0,0,1,full bed
4,4,Bo Phut Resort and Spa - SHA Plus,Bophut,9.3,Wonderful,294.0,9.6,621072,Unknown,0,0,0,0,1,double
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3460,3460,Circular House,"Boat Quay, Singapore",6.5,Review score,1.0,0.0,209678,Single,0,0,0,0,2,twin beds
3461,3461,Beary Best! Kampong Glam,"Kampong Glam, Singapore",6.4,Review score,362.0,0.0,118712,Single,0,0,1,0,2,twin beds
3462,3462,Ambassador Transit Hotel - Terminal 2,"Changi, Singapore",8.1,Very Good,26.0,8.9,1177140,Single,0,0,1,0,2,twin beds
3463,3463,K2 Guesthouse Central,"Jalan Besar, Singapore",6.6,Review score,114.0,0.0,227402,Single,0,0,0,0,2,twin beds
3464,3464,Heritage Collection on Boat Quay - Quayside Wi...,"Boat Quay, Singapore",8.6,Excellent,410.0,9.0,648803,Loft,0,0,0,1,2,full beds

In [3]:
bookings['room_score'] = bookings['room_score'].fillna(0)

In [4]:
bookings

,Unnamed: 0,hotel,location,rating,review,no_of_reviews,room_score,price,room_category,balcony,sea_view,shared_bathroom,no_window,bed_count,bed_type
0,0,Krabi La Playa Resort - SHA Plus,Ao Nang Beach,8.2,Very Good,141.0,8.6,146026,Deluxe,0,0,0,0,1,double
1,1,KC Beach Club & Pool Villas,"Chaweng City Center , Chaweng",7.1,Good,193.0,0.0,215304,Double,1,1,0,0,1,queen bed
2,2,Rawai VIP Villas & Kids Park,Rawai Beach,8.3,Very Good,63.0,8.9,435384,Unknown,0,0,0,0,2,queen beds
3,3,"FuramaXclusive Sathorn, Bangkok","Bang Rak, Bangkok",7.7,Good,1.0,8.1,146240,Double,0,0,0,0,1,full bed
4,4,Bo Phut Resort and Spa - SHA Plus,Bophut,9.3,Wonderful,294.0,9.6,621072,Unknown,0,0,0,0,1,double
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3460,3460,Circular House,"Boat Quay, Singapore",6.5,Review score,1.0,0.0,209678,Single,0,0,0,0,2,twin beds
3461,3461,Beary Best! Kampong Glam,"Kampong Glam, Singapore",6.4,Review score,362.0,0.0,118712,Single,0,0,1,0,2,twin beds
3462,3462,Ambassador Transit Hotel - Terminal 2,"Changi, Singapore",8.1,Very Good,26.0,8.9,1177140,Single,0,0,1,0,2,twin beds
3463,3463,K2 Guesthouse Central,"Jalan Besar, Singapore",6.6,Review score,114.0,0.0,227402,Single,0,0,0,0,2,twin beds
3464,3464,Heritage Collection on Boat Quay - Quayside Wi...,"Boat Quay, Singapore",8.6,Excellent,410.0,9.0,648803,Loft,0,0,0,1,2,full beds

In [5]:
bookings['price'] = bookings['price']*0.75

In [6]:
bookings['price']

0       109519.50
1       161478.00
2       326538.00
3       109680.00
4       465804.00
          ...
3460    157258.50
3461     89034.00
3462    882855.00
3463    170551.50
3464    486602.25
Name: price, Length: 3465, dtype: float64

In [39]:
bookings['hotel'] = bookings['hotel'].fillna('Unknown')

In [40]:
bookings

,hotel,location,rating,review,no_of_reviews,room_score,price,room_category,balcony,sea_view,shared_bathroom,no_window,bed_count,bed_type
0,Krabi La Playa Resort - SHA Plus,Ao Nang Beach,8.2,Very Good,141.0,8.6,146026,Deluxe,0,0,0,0,1,double
1,KC Beach Club & Pool Villas,"Chaweng City Center , Chaweng",7.1,Good,193.0,0.0,215304,Double,1,1,0,0,1,queen bed
2,Rawai VIP Villas & Kids Park,Rawai Beach,8.3,Very Good,63.0,8.9,435384,NaN,0,0,0,0,2,queen beds
3,"FuramaXclusive Sathorn, Bangkok","Bang Rak, Bangkok",7.7,Good,1.0,8.1,146240,Double,0,0,0,0,1,full bed
4,Bo Phut Resort and Spa - SHA Plus,Bophut,9.3,Wonderful,294.0,9.6,621072,NaN,0,0,0,0,1,double
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3460,Circular House,"Boat Quay, Singapore",6.5,Review score,1.0,0.0,209678,Single,0,0,0,0,2,twin beds
3461,Beary Best! Kampong Glam,"Kampong Glam, Singapore",6.4,Review score,362.0,0.0,118712,Single,0,0,1,0,2,twin beds
3462,Ambassador Transit Hotel - Terminal 2,"Changi, Singapore",8.1,Very Good,26.0,8.9,1177140,Single,0,0,1,0,2,twin beds
3463,K2 Guesthouse Central,"Jalan Besar, Singapore",6.6,Review score,114.0,0.0,227402,Single,0,0,0,0,2,twin beds
3464,Heritage Collection on Boat Quay - Quayside Wi...,"Boat Quay, Singapore",8.6,Excellent,410.0,9.0,648803,Loft,0,0,0,1,2,full beds

In [42]:
bookings['rating'] = bookings['rating'].fillna(0)

In [43]:
bookings['review'] = bookings['review'].fillna('Zero')

In [44]:
bookings['no_of_reviews'] = bookings['no_of_reviews'].fillna(0)

In [45]:
bookings['room_category'] = bookings['room_category'].fillna('Unknown')

In [46]:
bookings['room_score'] = bookings['room_score'].fillna(0)

In [47]:
bookings['bed_type'] = bookings['bed_type'].fillna('Unknown')

In [48]:
bookings['bed_type'].hasnans

False

In [7]:
bookings.to_csv('bookings.csv')